#ifndef PASSWORD_MODES_H
#define PASSWORD_MODES_H

#include <stdint.h>
namespace Mantids29 { namespace Authentication {

/**
 * @brief The Function enum defines the supported password hashing and authentication functions.
 *
 * The Function enum defines the supported password hashing and authentication functions. Each function is assigned a numerical value that can be used to specify the function when calling a related function.
 *
 * The available functions are:
 * - FN_NOTFOUND: Not found or invalid function.
 * - FN_PLAIN: Plain-text password storage (not recommended).
 * - FN_SHA256: Password hashed with SHA-256 algorithm.
 * - FN_SHA512: Password hashed with SHA-512 algorithm.
 * - FN_SSHA256: Password hashed with salted SHA-256 algorithm.
 * - FN_SSHA512: Password hashed with salted SHA-512 algorithm.
 * - FN_GAUTHTIME: Time-based one-time password (TOTP) generated by Google Authenticator.
 */
enum Function
{
    FN_NOTFOUND=500,
    FN_PLAIN=0,
    FN_SHA256=1,
    FN_SHA512=2,
    FN_SSHA256=3,
    FN_SSHA512=4,
    FN_GAUTHTIME=5
};
}}

#endif // PASSWORD_MODES_H
